apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-user-management
  labels:
    app: k8s-user-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-user-management
  template:
    metadata:
      labels:
        app: k8s-user-management
    spec:
      containers:
      - name: k8s-user-management
        image: k8s-user-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-user-management
spec:
  selector:
    app: k8s-user-management
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer 