apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  database-url: "postgresql://postgres:postgres@postgres:5432/k8s_users"
  jwt-secret: "your-secure-jwt-secret"
  postgres-user: "postgres"
  postgres-password: "postgres" 